default: &default
  adapter: postgresql
  host: localhost 
  port: 5432
  pool: 5
  timeout: 5000
  user: postgres
  password: 

development:
  <<: *default
  database: pizza_development

test:
  <<: *default
  database: pizza_test

production:
  database: pizza
  username: pizza
  password: 
  
